version: 2

sources:
  - name: STAGING
    database: STAGING
    schema: PUBLIC
    tables:
      - name: olist_customers_dataset
      - name: olist_geolocation_dataset
      - name: olist_order_items_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_reviews_dataset
      - name: olist_orders_dataset
      - name: olist_products_dataset
      - name: olist_sellers_dataset
      
